# Generated by Django 4.1.5 on 2023-01-13 08:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('lname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('cordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email address')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspension status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('no_show_count', models.IntegerField(default=0, verbose_name='Number of failed picked up')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item name')),
                ('description', models.TextField(null=True, verbose_name='Item description')),
                ('category', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item category')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Item status')),
                ('transaction_type', models.CharField(choices=[('Offer', 'Giver'), ('Request', 'Recipient')], default='', max_length=50, verbose_name='Offer type')),
                ('cordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('quantity', models.IntegerField(default=0, verbose_name='Item quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.userprofile')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
