# Generated by Django 4.1.5 on 2023-01-11 12:27

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.  Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has completed the email verification process to allow login.', verbose_name='verified')),
                ('fname', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('lname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('cordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone Number')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspension status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('no_show_count', models.IntegerField(default=0, verbose_name='Number of failed picked up')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item name')),
                ('description', models.TextField(null=True, verbose_name='Item description')),
                ('category', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item category')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Item status')),
                ('transaction_type', models.CharField(choices=[('Offer', 'Giver'), ('Request', 'Recipient')], default='', max_length=50, verbose_name='Offer type')),
                ('cordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('quantity', models.IntegerField(default=0, verbose_name='Item quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
