# Generated by Django 4.1.5 on 2023-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
