# Generated by Django 4.1.5 on 2023-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_item_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
