# Generated by Django 4.1.5 on 2023-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_item_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Item status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Offer type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
    ]
