# Generated by Django 4.1.5 on 2023-01-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False),
        ),
    ]
