# Generated by Django 4.1.5 on 2023-01-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='item',
            name='transaction_type',
            field=models.CharField(choices=[('Offer', 'Giver'), ('Request', 'Recipient')], default='', max_length=50, verbose_name='Offer type'),
        ),
    ]
