# Generated by Django 4.1.5 on 2023-06-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_item_location_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
